import BookMark from "../entities/BookMark"

const getAllBookMarks = async () => {
    const bookMarks: BookMark[] = [
        new BookMark("The Great Gatsby", "great_gatsby_thumbnail.jpg", "F. Scott Fitzgerald", [
            { nth: 1, name: "Chapter 1", flaged: false },
            { nth: 2, name: "Chapter 2", flaged: false },
            { nth: 3, name: "Chapter 3", flaged: true },
            { nth: 4, name: "Chapter 4", flaged: false },
            { nth: 5, name: "Chapter 5", flaged: false },
        ], new Date("2022-01-01"), new Date("2022-01-01")),
        new BookMark("To Kill a Mockingbird", "to_kill_a_mockingbird_thumbnail.jpg", "Harper Lee", [{ nth: 1, name: "Chapter 1", flaged: false },
        { nth: 2, name: "Chapter 2", flaged: false },
        { nth: 3, name: "Chapter 3", flaged: false },
        { nth: 4, name: "Chapter 4", flaged: true },
        { nth: 5, name: "Chapter 5", flaged: false },
        { nth: 6, name: "Chapter 6", flaged: false },
        { nth: 7, name: "Chapter 7", flaged: false },
        { nth: 8, name: "Chapter 8", flaged: false }
        ], new Date("2022-01-02"), new Date("2022-01-02")),
        new BookMark("1984", "1984_thumbnail.jpg", "George Orwell", [{ nth: 1, name: "Chapter 1", flaged: false },
        { nth: 2, name: "Chapter 2", flaged: false },
        { nth: 3, name: "Chapter 3", flaged: false },
        { nth: 4, name: "Chapter 4", flaged: false },
        { nth: 5, name: "Chapter 5", flaged: false },
        { nth: 6, name: "Chapter 6", flaged: true },
        { nth: 7, name: "Chapter 7", flaged: false },
        { nth: 8, name: "Chapter 8", flaged: false },
        { nth: 9, name: "Chapter 9", flaged: false },
        { nth: 10, name: "Chapter 10", flaged: false }], new Date("2022-01-03"), new Date("2022-01-03")),
        new BookMark("The Great Gatsby", "great_gatsby_thumbnail.jpg", "F. Scott Fitzgerald", [
            { nth: 1, name: "Chapter 1", flaged: true },
            { nth: 2, name: "Chapter 2", flaged: false },
            { nth: 3, name: "Chapter 3", flaged: false },
            { nth: 4, name: "Chapter 4", flaged: false },
            { nth: 5, name: "Chapter 5", flaged: false },
            { nth: 6, name: "Chapter 6", flaged: false },
            { nth: 7, name: "Chapter 7", flaged: false },
            { nth: 8, name: "Chapter 8", flaged: false },
            { nth: 9, name: "Chapter 9", flaged: false },
            { nth: 10, name: "Chapter 10", flaged: false }
        ], new Date("2022-01-01"), new Date("2022-01-01")),
        new BookMark("To Kill a Mockingbird", "to_kill_a_mockingbird_thumbnail.jpg", "Harper Lee", [
            { nth: 1, name: "Chapter 1", flaged: false },
            { nth: 2, name: "Chapter 2", flaged: false },
            { nth: 3, name: "Chapter 3", flaged: false },
            { nth: 4, name: "Chapter 4", flaged: false },
            { nth: 5, name: "Chapter 5", flaged: false },
            { nth: 6, name: "Chapter 6", flaged: false },
            { nth: 7, name: "Chapter 7", flaged: false },
            { nth: 8, name: "Chapter 8", flaged: true },
            { nth: 9, name: "Chapter 9", flaged: false },
            { nth: 10, name: "Chapter 10", flaged: false },
            { nth: 11, name: "Chapter 11", flaged: false },
            { nth: 12, name: "Chapter 12", flaged: false },
            { nth: 13, name: "Chapter 13", flaged: false },
            { nth: 14, name: "Chapter 14", flaged: false },
            { nth: 15, name: "Chapter 15", flaged: false },
            { nth: 16, name: "Chapter 16", flaged: false },
            { nth: 17, name: "Chapter 17", flaged: false },
            { nth: 18, name: "Chapter 18", flaged: false },
            { nth: 19, name: "Chapter 19", flaged: false },
            { nth: 20, name: "Chapter 20", flaged: false },
        ], new Date("2022-01-02"), new Date("2022-01-02")),
        new BookMark("1984", "1984_thumbnail.jpg", "George Orwell", [
            { nth: 1, name: "Chapter 1", flaged: false },
            { nth: 2, name: "Chapter 2", flaged: false },
            { nth: 3, name: "Chapter 3", flaged: false },
            { nth: 4, name: "Chapter 4", flaged: false },
            { nth: 5, name: "Chapter 5", flaged: false },
            { nth: 6, name: "Chapter 6", flaged: false },
            { nth: 7, name: "Chapter 7", flaged: false },
            { nth: 8, name: "Chapter 8", flaged: false },
            { nth: 9, name: "Chapter 9", flaged: false },
            { nth: 10, name: "Chapter 10", flaged: false },
            { nth: 11, name: "Chapter 11", flaged: false },
            { nth: 12, name: "Chapter 12", flaged: false },
            { nth: 13, name: "Chapter 13", flaged: true },
            { nth: 14, name: "Chapter 14", flaged: false },
            { nth: 15, name: "Chapter 15", flaged: false }
        ], new Date("2022-01-03"), new Date("2022-01-03")),
        new BookMark("Moby Dick", "moby_dick_thumbnail.jpg", "Herman Melville", [
            { nth: 1, name: "Chapter 1", flaged: false },
            { nth: 2, name: "Chapter 2", flaged: false },
            { nth: 3, name: "Chapter 3", flaged: false },
            { nth: 4, name: "Chapter 4", flaged: false },
            { nth: 5, name: "Chapter 5", flaged: false },
            { nth: 6, name: "Chapter 6", flaged: false },
            { nth: 7, name: "Chapter 7", flaged: true },
            { nth: 8, name: "Chapter 8", flaged: false },
            { nth: 9, name: "Chapter 9", flaged: false },
            { nth: 10, name: "Chapter 10", flaged: false },
            { nth: 11, name: "Chapter 11", flaged: false },
            { nth: 12, name: "Chapter 12", flaged: false },
        ], new Date("2022-01-04"), new Date("2022-01-04")),
        new BookMark("War and Peace", "war_and_peace_thumbnail.jpg", "Leo Tolstoy", [
            { nth: 1, name: "Chapter 1", flaged: false },
            { nth: 2, name: "Chapter 2", flaged: true },
            { nth: 3, name: "Chapter 3", flaged: false },
            { nth: 4, name: "Chapter 4", flaged: false },], new Date("2022-01-05"), new Date("2022-01-05")),
    ]
    return bookMarks
}

export default getAllBookMarks