import BookMark from "../entities/BookMark"

const getAllBookMarks = async () => {
    const bookMarks: BookMark[] = [
        new BookMark("name", "thumbnail", "author", [], new Date(), new Date()),
        new BookMark("The Great Gatsby", "great_gatsby_thumbnail.jpg", "F. Scott Fitzgerald", [
            { nth: 1, name: "Chapter 1" },
            { nth: 2, name: "Chapter 2" },
            { nth: 3, name: "Chapter 3" },
            { nth: 4, name: "Chapter 4" },
            { nth: 5, name: "Chapter 5" },
        ], new Date("2022-01-01"), new Date("2022-01-01")),
        new BookMark("To Kill a Mockingbird", "to_kill_a_mockingbird_thumbnail.jpg", "Harper Lee", [{ nth: 1, name: "Chapter 1" },
        { nth: 2, name: "Chapter 2" },
        { nth: 3, name: "Chapter 3" },
        { nth: 4, name: "Chapter 4" },
        { nth: 5, name: "Chapter 5" },
        { nth: 6, name: "Chapter 6" },
        { nth: 7, name: "Chapter 7" },
        { nth: 8, name: "Chapter 8" }
        ], new Date("2022-01-02"), new Date("2022-01-02")),
        new BookMark("1984", "1984_thumbnail.jpg", "George Orwell", [{ nth: 1, name: "Chapter 1" },
        { nth: 2, name: "Chapter 2" },
        { nth: 3, name: "Chapter 3" },
        { nth: 4, name: "Chapter 4" },
        { nth: 5, name: "Chapter 5" },
        { nth: 6, name: "Chapter 6" },
        { nth: 7, name: "Chapter 7" },
        { nth: 8, name: "Chapter 8" },
        { nth: 9, name: "Chapter 9" },
        { nth: 10, name: "Chapter 10" }], new Date("2022-01-03"), new Date("2022-01-03")),
        new BookMark("The Great Gatsby", "great_gatsby_thumbnail.jpg", "F. Scott Fitzgerald", [
            { nth: 1, name: "Chapter 1" },
            { nth: 2, name: "Chapter 2" },
            { nth: 3, name: "Chapter 3" },
            { nth: 4, name: "Chapter 4" },
            { nth: 5, name: "Chapter 5" },
            { nth: 6, name: "Chapter 6" },
            { nth: 7, name: "Chapter 7" },
            { nth: 8, name: "Chapter 8" },
            { nth: 9, name: "Chapter 9" },
            { nth: 10, name: "Chapter 10" }
        ], new Date("2022-01-01"), new Date("2022-01-01")),
        new BookMark("To Kill a Mockingbird", "to_kill_a_mockingbird_thumbnail.jpg", "Harper Lee", [
            { nth: 1, name: "Chapter 1" },
            { nth: 2, name: "Chapter 2" },
            { nth: 3, name: "Chapter 3" },
            { nth: 4, name: "Chapter 4" },
            { nth: 5, name: "Chapter 5" },
            { nth: 6, name: "Chapter 6" },
            { nth: 7, name: "Chapter 7" },
            { nth: 8, name: "Chapter 8" },
            { nth: 9, name: "Chapter 9" },
            { nth: 10, name: "Chapter 10" },
            { nth: 11, name: "Chapter 11" },
            { nth: 12, name: "Chapter 12" },
            { nth: 13, name: "Chapter 13" },
            { nth: 14, name: "Chapter 14" },
            { nth: 15, name: "Chapter 15" },
            { nth: 16, name: "Chapter 16" },
            { nth: 17, name: "Chapter 17" },
            { nth: 18, name: "Chapter 18" },
            { nth: 19, name: "Chapter 19" },
            { nth: 20, name: "Chapter 20" },
        ], new Date("2022-01-02"), new Date("2022-01-02")),
        new BookMark("1984", "1984_thumbnail.jpg", "George Orwell", [
            { nth: 1, name: "Chapter 1" },
            { nth: 2, name: "Chapter 2" },
            { nth: 3, name: "Chapter 3" },
            { nth: 4, name: "Chapter 4" },
            { nth: 5, name: "Chapter 5" },
            { nth: 6, name: "Chapter 6" },
            { nth: 7, name: "Chapter 7" },
            { nth: 8, name: "Chapter 8" },
            { nth: 9, name: "Chapter 9" },
            { nth: 10, name: "Chapter 10" },
            { nth: 11, name: "Chapter 11" },
            { nth: 12, name: "Chapter 12" },
            { nth: 13, name: "Chapter 13" },
            { nth: 14, name: "Chapter 14" },
            { nth: 15, name: "Chapter 15" }
        ], new Date("2022-01-03"), new Date("2022-01-03")),
        new BookMark("Moby Dick", "moby_dick_thumbnail.jpg", "Herman Melville", [
            { nth: 1, name: "Chapter 1" },
            { nth: 2, name: "Chapter 2" },
            { nth: 3, name: "Chapter 3" },
            { nth: 4, name: "Chapter 4" },
            { nth: 5, name: "Chapter 5" },
            { nth: 6, name: "Chapter 6" },
            { nth: 7, name: "Chapter 7" },
            { nth: 8, name: "Chapter 8" },
            { nth: 9, name: "Chapter 9" },
            { nth: 10, name: "Chapter 10" },
            { nth: 11, name: "Chapter 11" },
            { nth: 12, name: "Chapter 12" },
        ], new Date("2022-01-04"), new Date("2022-01-04")),
        new BookMark("War and Peace", "war_and_peace_thumbnail.jpg", "Leo Tolstoy", [
            { nth: 1, name: "Chapter 1" },
            { nth: 2, name: "Chapter 2" },
            { nth: 3, name: "Chapter 3" },
            { nth: 4, name: "Chapter 4" },], new Date("2022-01-05"), new Date("2022-01-05")),
    ]
    return bookMarks
}

export default getAllBookMarks